# Generated by Django 5.1.1 on 2024-10-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(default='', max_length=150, verbose_name='Content')),
                ('head1', models.TextField(default='', max_length=50, verbose_name='Head1')),
                ('head2', models.TextField(default='', max_length=50, verbose_name='Head2')),
                ('head1_content', models.TextField(default='', max_length=150, verbose_name='Head1 Content')),
                ('head2_content', models.TextField(default='', max_length=150, verbose_name='Head2 Content')),
                ('publishedAt', models.DateField(auto_now_add=True, verbose_name='Published At')),
                ('updatedAt', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('image', models.ImageField(default='', upload_to='blog/images', verbose_name='Image')),
            ],
        ),
    ]
