# Generated by Django 5.1.1 on 2024-10-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_content_alter_blogpost_head1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='', max_length=1000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1_content',
            field=models.TextField(default='', verbose_name='Head1 Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2_content',
            field=models.TextField(default='', verbose_name='Head2 Content'),
        ),
    ]
