# Generated by Django 5.1.1 on 2024-10-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_content_alter_blogpost_head1_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='Author'),
        ),
    ]
