# Generated by Django 5.1 on 2024-09-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_tracker_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='tracker_id',
            new_name='track_id',
        ),
    ]
