# Generated by Django 5.1 on 2024-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+92 000 000 0000', max_length=13, verbose_name='Phone')),
                ('description', models.TextField(default='', max_length=150, verbose_name='Description')),
                ('interest', models.CharField(default='', max_length=50, verbose_name='Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_person', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(default='', max_length=150, verbose_name='Address')),
                ('city', models.CharField(default='', max_length=50, verbose_name='City')),
                ('state', models.CharField(default='', max_length=50, verbose_name='State')),
                ('zip_code', models.IntegerField(default=0, verbose_name='Zip')),
                ('phone', models.CharField(default='+92 000 000 0000', max_length=13, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('sku', models.CharField(default='', max_length=50, verbose_name='SKU')),
                ('category', models.CharField(default='', max_length=50, verbose_name='Category')),
                ('sub_category', models.CharField(default='', max_length=50, verbose_name='Sub-Category')),
                ('stock', models.FloatField(default=0, verbose_name='Stock')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('description', models.TextField(default='', max_length=150, verbose_name='Description')),
                ('image', models.ImageField(default='', upload_to='shop/images', verbose_name='Image')),
                ('publishedAt', models.DateField(default='', verbose_name='Published At')),
            ],
        ),
    ]
