# Generated by Django 5.1 on 2024-09-03 10:48

import django.core.serializers.json
import json.decoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default={}, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Order Items'),
        ),
    ]
