# Generated by Django 5.1 on 2024-09-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('tracker_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.TextField(default='', max_length=150, verbose_name='Order Status')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
    ]
