# Generated by Django 5.1 on 2024-09-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_tracker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracker',
            new_name='Track',
        ),
    ]
