# Generated by Django 5.1 on 2024-09-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_track_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='order',
            new_name='order_id',
        ),
    ]
