# Generated by Django 5.1 on 2024-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_order_track_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='status_description',
            field=models.TextField(default='', max_length=150, verbose_name='Status Description'),
        ),
        migrations.AlterField(
            model_name='track',
            name='order_status',
            field=models.CharField(default='', max_length=50, verbose_name='Order Status'),
        ),
    ]
