# Generated by Django 5.1 on 2024-09-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_track_status_description_alter_track_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
