# Generated by Django 5.1 on 2024-08-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone No.')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time')),
            ],
        ),
    ]
