# Generated by Django 5.1 on 2024-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default=None, max_length=50, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='phone.'),
        ),
    ]
