# Generated by Django 5.1 on 2024-08-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_contact_name_contact_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='datetime',
            new_name='date_n_time',
        ),
    ]
