# Generated by Django 5.1 on 2024-08-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_datetime_contact_date_n_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_n_time',
            new_name='date',
        ),
    ]
