# Generated by Django 5.1 on 2024-08-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_date_n_time_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='date_n_time',
        ),
    ]
