# Generated by Django 5.1 on 2024-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_date_n_time_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_n_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date_n_time'),
        ),
    ]
