# Generated by Django 5.1 on 2024-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_contact_date_contact_date_n_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_n_time',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time'),
        ),
    ]
